# Generated by Django 4.2.3 on 2024-02-21 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Имя исполнителя')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(verbose_name='Дата создания')),
                ('priority', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], verbose_name='Приоритет')),
                ('header', models.CharField(verbose_name='Заголовок')),
                ('comment', models.CharField(verbose_name='Комментарий')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.executor', verbose_name='Исполнитель')),
            ],
        ),
    ]
